services:
#  elasticsearch:
#    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
#    environment:
#      - 'ELASTIC_PASSWORD=secret'
#      - 'discovery.type=single-node'
#      - 'xpack.security.enabled=false'
#    ports:
#      - '9200'
#      - '9300'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=skillseeker'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8081:8080
    restart: always
    depends_on:
      - postgres
#  redis:
#    image: 'redis:latest'
#    ports:
#      - '6379'