spring:
  config:
    import: optional:file:../docker/.env[.properties]
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${PG_PORT}/${PG_DB}?currentSchema=${PG_SCHEMA}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration/postgres